use_frameworks!

platform :ios, '8.0'

target 'SJPlaybackListController_Example' do
  pod 'SJPlaybackListController', :path => '../'

  target 'SJPlaybackListController_Tests' do
    inherit! :search_paths

    
  end
end
