#use_frameworks!

platform :ios, '8.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end

target 'SJPlaybackListController_Example' do
  pod 'SJPlaybackListController', :path => '../'
  pod 'SJBaseVideoPlayer', :path => '../../SJBaseVideoPlayer'
  pod 'Masonry', :inhibit_warnings => true
end
